/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Calculator;

/**
 *
 * @author sharo
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    double NumEnter1;
    double NumEnter2;
    double Result;
    String Op;

    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtResult = new javax.swing.JTextField();
        jbtnCE = new javax.swing.JButton();
        jbtnBS = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnPM = new javax.swing.JButton();
        jbtnPlus = new javax.swing.JButton();
        jbtnDG9 = new javax.swing.JButton();
        jbtnDG8 = new javax.swing.JButton();
        jbtnDG7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jbtnDG6 = new javax.swing.JButton();
        jbtnDG5 = new javax.swing.JButton();
        jbtnDG4 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jbtnDG3 = new javax.swing.JButton();
        jbtnDG2 = new javax.swing.JButton();
        jbtnDG1 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jbtnDG0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtResult.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jtxtResult.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtResultActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtResult, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 310, 60));

        jbtnCE.setBackground(new java.awt.Color(204, 204, 204));
        jbtnCE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnCE.setText("CE");
        jbtnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCEActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 70, 70));

        jbtnBS.setBackground(new java.awt.Color(204, 204, 204));
        jbtnBS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnBS.setText("B");
        jbtnBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBSActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnBS, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 70, 70));

        jbtnC.setBackground(new java.awt.Color(204, 204, 204));
        jbtnC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnC.setText("C");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 70, 70));

        jbtnPM.setBackground(new java.awt.Color(204, 204, 204));
        jbtnPM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPM.setText("+/-");
        jbtnPM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPMActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPM, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 70, 70));

        jbtnPlus.setBackground(new java.awt.Color(204, 204, 204));
        jbtnPlus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnPlus.setText("+");
        jbtnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlusActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 70, 70));

        jbtnDG9.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG9.setText("9");
        jbtnDG9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG9ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG9, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 70, 70));

        jbtnDG8.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG8.setText("8");
        jbtnDG8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG8ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 70, 70));

        jbtnDG7.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG7.setText("7");
        jbtnDG7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG7ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 70, 70));

        jButton9.setBackground(new java.awt.Color(204, 204, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText("-");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 70, 70));

        jbtnDG6.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG6.setText("6");
        jbtnDG6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG6ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 70, 70));

        jbtnDG5.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG5.setText("5");
        jbtnDG5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG5ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 70, 70));

        jbtnDG4.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG4.setText("4");
        jbtnDG4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG4ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 70, 70));

        jButton13.setBackground(new java.awt.Color(204, 204, 204));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton13.setText("*");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 70, 70));

        jbtnDG3.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG3.setText("3");
        jbtnDG3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG3ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 70, 70));

        jbtnDG2.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG2.setText("2");
        jbtnDG2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG2ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 70, 70));

        jbtnDG1.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG1.setText("1");
        jbtnDG1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG1ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 70, 70));

        jButton17.setBackground(new java.awt.Color(204, 204, 204));
        jButton17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton17.setText("/");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, 70, 70));

        jButton18.setBackground(new java.awt.Color(204, 204, 204));
        jButton18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton18.setText("=");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 70, 70));

        jButton19.setBackground(new java.awt.Color(204, 204, 204));
        jButton19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton19.setText(".");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 70, 70));

        jbtnDG0.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDG0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jbtnDG0.setText("0");
        jbtnDG0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDG0ActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnDG0, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 70, 70));

        setSize(new java.awt.Dimension(371, 518));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EnterNumber(String q) {

        String Nums = jtxtResult.getText() + q;
        jtxtResult.setText(Nums);

    }

    private void jbtnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCEActionPerformed
        jtxtResult.setText("");

        String Fn, Sn;

        Fn = String.valueOf(NumEnter1);
        Sn = String.valueOf(NumEnter2);

        Fn = "";
        Sn = "";


    }//GEN-LAST:event_jbtnCEActionPerformed

    private void jbtnBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBSActionPerformed
        // TODO add your handling code here:
        String backSp = null;

        if (jtxtResult.getText().length() > 0) {
            StringBuilder sb = new StringBuilder(jtxtResult.getText());
            sb.deleteCharAt(jtxtResult.getText().length() - 1);
            backSp = sb.toString();
            jtxtResult.setText(backSp);
        }
    }//GEN-LAST:event_jbtnBSActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtResult.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnPMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPMActionPerformed
        double nums = Double.parseDouble(String.valueOf(jtxtResult.getText()));
        nums = nums * (-1);
        jtxtResult.setText(String.valueOf(nums));

    }//GEN-LAST:event_jbtnPMActionPerformed

    private void jbtnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlusActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "+";

    }//GEN-LAST:event_jbtnPlusActionPerformed

    private void jbtnDG9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG9ActionPerformed
        EnterNumber("9");
    }//GEN-LAST:event_jbtnDG9ActionPerformed

    private void jbtnDG8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG8ActionPerformed
        // TODO add your handling code here:
        EnterNumber("8");
    }//GEN-LAST:event_jbtnDG8ActionPerformed

    private void jbtnDG7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG7ActionPerformed
        EnterNumber("7");
    }//GEN-LAST:event_jbtnDG7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        //DO a TOdd your handling code here:
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "-";
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jbtnDG6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG6ActionPerformed
        EnterNumber("6");
    }//GEN-LAST:event_jbtnDG6ActionPerformed

    private void jbtnDG5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG5ActionPerformed
        EnterNumber("5");
    }//GEN-LAST:event_jbtnDG5ActionPerformed

    private void jbtnDG4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG4ActionPerformed
        EnterNumber("4");
    }//GEN-LAST:event_jbtnDG4ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "*";

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jbtnDG3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG3ActionPerformed
        // TODO add your handling code here:
        EnterNumber("3");
    }//GEN-LAST:event_jbtnDG3ActionPerformed

    private void jbtnDG2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG2ActionPerformed
        // TODO add your handling code here:
        EnterNumber("2");
    }//GEN-LAST:event_jbtnDG2ActionPerformed

    private void jbtnDG1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG1ActionPerformed
        // TODO add your handling code here:

        EnterNumber("1");
    }//GEN-LAST:event_jbtnDG1ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        NumEnter1 = Double.parseDouble(jtxtResult.getText());
        jtxtResult.setText("");
        Op = "/";
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed

        NumEnter2 = Double.parseDouble(jtxtResult.getText());

        if (Op == "+") {
            Result = NumEnter1 + NumEnter2;
            jtxtResult.setText(String.valueOf(Result));

        } else if (Op == "-") {
            Result = NumEnter1 - NumEnter2;
            jtxtResult.setText(String.valueOf(Result));

        } else if (Op == "*") {
            Result = NumEnter1 * NumEnter2;
            jtxtResult.setText(String.valueOf(Result));

        } else if (Op == "/") {
            Result = NumEnter1 / NumEnter2;
            jtxtResult.setText(String.valueOf(Result));

        }


    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        if (!jtxtResult.getText().contains(".")) {

            jtxtResult.setText(jtxtResult.getText() + jButton19.getText());
        }
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jbtnDG0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDG0ActionPerformed
        // TODO add your handling code here:
        EnterNumber("0");
    }//GEN-LAST:event_jbtnDG0ActionPerformed

    private void jtxtResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jbtnBS;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnCE;
    private javax.swing.JButton jbtnDG0;
    private javax.swing.JButton jbtnDG1;
    private javax.swing.JButton jbtnDG2;
    private javax.swing.JButton jbtnDG3;
    private javax.swing.JButton jbtnDG4;
    private javax.swing.JButton jbtnDG5;
    private javax.swing.JButton jbtnDG6;
    private javax.swing.JButton jbtnDG7;
    private javax.swing.JButton jbtnDG8;
    private javax.swing.JButton jbtnDG9;
    private javax.swing.JButton jbtnPM;
    private javax.swing.JButton jbtnPlus;
    private javax.swing.JTextField jtxtResult;
    // End of variables declaration//GEN-END:variables
}
